#!/usr/bin/ruby
require 'irb/completion'
require 'irb/ext/save-history'

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT] = true

class Object
  # list methods which aren't in superclass
  def local_methods(obj = self)
    (obj.methods - obj.class.superclass.instance_methods).sort
  end
end

def stopwatch(times = 1, &block)
  start = Time.now
  times.times { yield }
  finish = Time.now - start

  if times == 1
    puts "Took #{finish} to complete once"
  else
    puts "Took #{finish} to complete #{times} times"
  end
end

load "~/.railsrc" if defined?(Rails)
