[tools]
usage = "latest"
ruby = "latest"
awscli = "latest"
node = "latest"
babashka = "latest"
java = "latest"
python = "latest"

[settings]
verbose = false
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
